### ISSUE TITLE
Two features to Reporting area

### ISSUE THREAD

**Issue by alexmccauley** [saplingai/sapling-samples#2]
We (Brightfox, gobrightfox.com) are an educational tutoring center where the tutors write summary notes about what happened, mostly for parents to read. We want these notes to be high quality, so we implemented Sapling and require the instructors to clear all underlined portions by Sapling (Accept or Ignore) before submitting. 

We don't want this to be a burden on them which makes their job much worse. We would like to keep adding more dictionary words to improve the usefulness.

1) In my opinion "Accept to Ignore ratio" is the signal of success. We want as many accepts as possible with very few ignores. It would be nice to add this chart, which seems like it should be easy. This is the main metric I will be monitoring.

2) It would be nice to see the list of actual ignores so we can add words to the Dictionary. For example, if there is a technical word in Math like "L'hospital's Rule" that the instructors keep having to click Ignore over and over again, I should be able to see that, and add it to the Dictionary.

The list of ignored words would be something like:

l'hospital's rule (5) where 5 is the total count of times it's been ignored
sqrt3 (4)
microplasmal (3)
biopsy (3)  

<img width="1639" alt="User_Reporting___Sapling" src="https://github.com/saplingai/sapling-samples/assets/18706469/3f7ffa0b-9f92-4d72-9ad8-c08a3cac0c72">

**Comment by saplingdev** [comment]
Hi @alexmccauley, we'll get back to you later this week with updates on both requests!

**Comment by rishabhmarya-work** [comment]
hi @alexmccauley , we've shipped an update to our website - you should now see an Accepts/Ignores graph as well.

**Comment by saplingdev** [comment]
Hi @alexmccauley, you can find ignores from multiple teammates (within the last 30 days) at the bottom of the team dictionary panel as suggested candidates to add to a team dictionary. We filter out common words and edits that get a noisy accept/reject ratio.
